### ISSUE TITLE
Use of uninitialized value $Bio::DB::NCBIHelper::HOSTBASE in concatenation (.) or string at /usr/share/perl5/Bio/DB/Query/GenBank.pm line 103.

### ISSUE THREAD

**Issue by jmartinsjrbr** [bioperl/Bio-DB-NCBIHelper#1]
We have update our bioperl version to 1.6923. Now, when we ran the local version of Guidance, an dna sequence multiple alignment software (http://guidance.tau.ac.il/), we get the following error:

"Use of uninitialized value $Bio::DB::NCBIHelper::HOSTBASE in concatenation (.) or string at /usr/share/perl5/Bio/DB/Query/GenBank.pm line 103."
"Use of uninitialized value $Bio::DB::NCBIHelper::HOSTBASE in concatenation (.) or string at /usr/share/perl5/Bio/DB/Query/GenBank.pm line 104."

Could provide any help?

Best regards,
Joaquim

**Comment by cjfields** [comment]
@jmartinsjrbr closing ticket out, assuming this is fixed.  Feel free to reopen if this isn't addressed.

**Comment by carandraug** [comment]
For what is worth, this was "fixed" with bioperl/bioperl-live@adebb794f1479a4f86106713ba5912ba
