### ISSUE TITLE
NCBI query fixes

### ISSUE THREAD

**Issue by cjfields** [bioperl/Bio-DB-NCBIHelper#4]
This is a placeholder issue for now. Fixes were added in 727f3a5890ec79c128492b2cf461e1379799b265, but the release of a new version is blocking until a new BioPerl release is made that includes https://github.com/bioperl/bioperl-live/commit/2ab201ffa90e0a51b957b994b300222d6aa72373.

**Comment by carandraug** [comment]
Adding a new property to Bio::DB::Query::WebQuery seems worth noting on the Changes file. Can you please add such note on that bioperl-live Changes file?

Also, I guess this means that the requirement for that upcoming version should be noted somewhere.

**Comment by cjfields** [comment]
@carandraug Yep that should be clarified, I can add this.  To be honest, on the surface there appears to be a *lot* of overlap with Bio::DB::Query::WebQuery and Bio::WebAgent functionality, it might be worth evaluating what modules require these.

**Comment by cjfields** [comment]
Fixed in the latest BioPerl release (v1.7.7) and here.
